export const BASE_STATUSES = {
  PENDING: "PENDING",
  ASSIGNED: "ASSIGNED",
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
  COMPLETED: "COMPLETED",
  EXPIRED: "EXPIRED",
};

export const ASSISTANCE_STATUSES = {
  PENDING: "PENDING",
  ASSIGNED: "ASSIGNED",
  COMPLETED: "COMPLETED",
  EXPIRED: "EXPIRED",
};

export const ROUTINE_REQUEST_STATUSES = {
  PENDING: "PENDING",
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
  COMPLETED: "COMPLETED",
};

export const SOCIAL_CHALLENGE_STATUSES = {
  ASSIGNED: "ASSIGNED",
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
  COMPLETED: "COMPLETED",
  EXPIRED: "EXPIRED",
};

export const COMPLAINT_STATUSES = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
};

export const REWARD_STATUSES = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  SHIPPED: "SHIPPED",
  DELIVERED: "DELIVERED",
};

export default {
  BASE_STATUSES,
  ASSISTANCE_STATUSES,
  ROUTINE_REQUEST_STATUSES,
  SOCIAL_CHALLENGE_STATUSES,
  COMPLAINT_STATUSES,
  REWARD_STATUSES,
};