export const BASE_STATUSES = {
  PENDING: "PENDING",
  ASSIGNED: "ASSIGNED",
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
  COMPLETED: "COMPLETED",
  EXPIRED: "EXPIRED",
};

export const ASSISTANCE_STATUSES = {
  PENDING: BASE_STATUSES.PENDING,
  ASSIGNED: BASE_STATUSES.ASSIGNED,
  COMPLETED: BASE_STATUSES.COMPLETED,
  EXPIRED: BASE_STATUSES.EXPIRED,
};

export const ROUTINE_REQUEST_STATUSES = {
  PENDING: BASE_STATUSES.PENDING,
  ACCEPTED: BASE_STATUSES.ACCEPTED,
  REJECTED: BASE_STATUSES.REJECTED,
  COMPLETED: BASE_STATUSES.COMPLETED,
};

export const SOCIAL_CHALLENGE_STATUSES = {
  ASSIGNED: BASE_STATUSES.ASSIGNED,
  ACCEPTED: BASE_STATUSES.ACCEPTED,
  REJECTED: BASE_STATUSES.REJECTED,
  COMPLETED: BASE_STATUSES.COMPLETED,
  EXPIRED: BASE_STATUSES.EXPIRED,
};

export const COMPLAINT_STATUSES = {
  PENDING: BASE_STATUSES.PENDING,
  APPROVED: "APPROVED",
  REJECTED: BASE_STATUSES.REJECTED,
};

export const REWARD_STATUSES = {
  PENDING: BASE_STATUSES.PENDING,
  APPROVED: "APPROVED",
  SHIPPED: "SHIPPED",
  DELIVERED: "DELIVERED",
};

const STATUSES = {
  BASE_STATUSES,
  ASSISTANCE_STATUSES,
  ROUTINE_REQUEST_STATUSES,
  SOCIAL_CHALLENGE_STATUSES,
  COMPLAINT_STATUSES,
  REWARD_STATUSES,
};

export default STATUSES;
